services:
  db:
    image: bigm
    restart: always
    container_name: bigm
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
# postgres://postgres:password@localhost:5432/app_db

volumes:
  postgres_data:
